### PR TITLE
Added microG and Play Store instructions

### PR DESCRIPTION
**Pull request by user0-07161**
Added microG and Play Store instructions. The result is a working Play Store.

### CODE REVIEW

**Comment by SciLor** [comment]
Thank you for your PR.
It's great, but I dislike the MEGA link. Is there any official source that can be used for it?

**Comment by user0-07161** [comment]
All apks from microG are from the official F-Droid microG Source. The Google Apps are from APKMirror.

**Comment by SciLor** [comment]
Please link to the original source

microG: https://microg.org/download.html
GApps: https://opengapps.org/

**Comment by user0-tb** [comment]
Thanks,

but with the OpenGapps packages there is a Problem: the package is flashable, but i can't flash it in the Box.

**Comment by user0-tb** [comment]
Also, you need an Special Version of the Play Store.

**Comment by user0-07161** [comment]
@SciLor Now the links are added and sources provided.

**Comment by user0-07161** [comment]
PR is ready for Review.

**Pull request merged**
